### ISSUE TITLE
Host metrics?

### ISSUE THREAD

**Issue by djskinner** [Rucknar/Guide_Rancher_Monitoring#1]
I just discovered this on the community-catalog. Thanks for the awesome work. I'm not getting any host metrics coming through. All green on the Prometheus status page and I've added `graphite.host` and restarted rancher server too. Any ideas?

**Comment by Rucknar** [comment]
Thanks for the feedback! When you say Host metrics, are you talking about the server metrics from the rancher server container or from the container hosts themselves?

If it's host level metrics, check on the Prometheus status page, do you see your hosts listed with a connection to port 9100? The node exporter should be running on that port and populating the 'node* set of metrics in Prometheus. 

If it's the rancher-server, check connectivity from the rancher server to InfluxDB on that port using telnet or netcat. The rancher server should be logging errors to it's console if it can't talk to the DB.

**Comment by djskinner** [comment]
I mean the Host Stats dashboard, the CPU / memory graphs.

Prometheus all looks good.

The rancher-server metrics are working by the looks.

**Comment by djskinner** [comment]
If I am seeing data come through on Prometheus for say `node_disk_read_time_ms` does that indicate it is working? Perhaps the graph queries are not working for me.

**Comment by Rucknar** [comment]
Yep, that should indicate Prometheus can scrape the node exporter. If you go into grafana, you should be able to test the data connection to Prometheus, choose the data sources page and run the test, should look like: 

<img width="952" alt="screen shot 2016-03-05 at 09 37 16" src="https://cloud.githubusercontent.com/assets/5539660/13546955/015077e8-e2b6-11e5-9d82-16c5799aac6a.png">

If that's all good then, do you have the list of servers to select from under the 'container hosts' label?
Should be able to filter as per below, try choosing a single server to see if any data comes up.

<img width="320" alt="screen shot 2016-03-05 at 09 37 04" src="https://cloud.githubusercontent.com/assets/5539660/13546964/213ffb0a-e2b6-11e5-993c-35c826d6d4b3.png">

**Comment by djskinner** [comment]
Yes all that looks fine. I can see my two Container Hosts in the dropbown but the graphs are empty and say 'No Datapoints'

**Comment by Rucknar** [comment]
What's the timeframe grafana is viewing? Try drop it to something like 15 mins. Struggling to think why this isn't working to be honest, if the data is there and grafana can talk to prometheus.

**Comment by djskinner** [comment]
I haven't managed to get it working across any timeframes. It's as if the data is there but the queries that generate the graphs do not return any data. Is it possible that the queries need changing depending upon the host environment?

**Comment by Rucknar** [comment]
It *shouldn't* be, i'm clearly missing something though. 

Back to basics, can you run the following query `node_boot_time` in Prometheus. It should return the hosts you're interested in viewing. 

Once that's confirmed, create a new graph in Grafana with just this query and Prometheus selected as a datasource, does it return any data?

**Comment by Rucknar** [comment]
Just noticed Prometheus 0.17 has been released, will re-deploy using that version. I'm wondering if those queries don't work. The above test is still valid though.

**Comment by djskinner** [comment]
That queries and graphs just fine. I upgraded the service to latest too.

**Comment by djskinner** [comment]
The queries in the dashboard work if I adjust them from 

```
node_load1{instance=~"$server"}
```

 to 

```
node_load1
```

**Comment by djskinner** [comment]
There is `node_load1`, `node_load15` and `node_load5` in Prometheus

**Comment by Rucknar** [comment]
Okay, $server is a grafana template object. It should populate that variable with a list of hosts. I'll do some debugging on my side, i suspect that query must be failing. Although... the fact you see the drop-down list for container hosts suggests it'w working.

**Comment by Rucknar** [comment]
Looks like it's broken in the latest prometheus. Just upgraded my reference build. I'll get a fix out tonight.

**Comment by Rucknar** [comment]
`node_load1{instance=~"^$server.*"}` should work fine. I'll update the graf-db shortly.

**Comment by Rucknar** [comment]
Slight delay. The above works but not then with the piping method i use. I'm going to do some updates to how the hosts are labelled in prometheus to resolve this. Should have a fix out tomorrow, your graphs can work with the above for now though.

**Comment by Rucknar** [comment]
RIght, updated pull request submitted @djskinner. 
It should now auto-discover hosts through DNS, and the server field in the graphs should also work.

https://github.com/rancher/community-catalog/pull/14

**Comment by Rucknar** [comment]
They are quick today! Merged.

**Comment by djskinner** [comment]
I deleted the stack and recreated it and all is working now. Thanks a lot for your help. Where is the best place to discuss separate issues? I would like to discuss locking it down so that not so much is available on public ports.

Thanks for the awesome piece of work and your help getting it in working order!

**Comment by Rucknar** [comment]
No worries @djskinner Glad you've found it useful. Happy to open anything related to that here if you so wish. In terms of locking it down, ideally i'd also like to keep as much within the rancher managed network as possible. It might be possible through tweaks to the config to limit the 9100+9104 ports used to expose metrics, i've not done much testing though in this area yet.

Grafana + Prometheus will need some sort of mapping out so you can get at them.
