### ISSUE TITLE
Monitoring my own metrics

### ISSUE THREAD

**Issue by utrack** [Rucknar/Guide_Rancher_Monitoring#2]
Hi! Not sure where to ask that but:
Is it possible to add my own services to Prometheus\Grafana bundle dynamically?

**Comment by Rucknar** [comment]
It sure is!

If it's just monitoring additional stacks/services you've got deployed in Rancher, then this can be done easily. If you duplicate the existing dashboard setup for Prometheus monitoring then you can update those cells to monitor the services you're interested in. If you wish to monitor more things....

### Prometheus 
The configuration in-place out of the box, is there to get you started but by all means you could fork the prom-conf repo and add in your own configuration, if you view the file that's there you will see how it's been done with DNS. More info on how to configure Prometheus can be found [here](https://prometheus.io/docs/operating/configuration/).

### Grafana
For this template, i've mapped in the grafana sqllite DB through the 'graf-db' container. 
You can copy this out of the container, or export the dashboards you want, all you need to do then is to 
import them on a re-fresh. Or alternatively you could bin off the graf-db container altogether and mount a volume in from the host.

**Comment by utrack** [comment]
Thanks!
It'd be awesome if the stack included push gateway from the box, but the fork would work too. Thank you :+1:
