### ISSUE TITLE
Rancher Graphite support

### ISSUE THREAD

**Issue by jmreicha** [Rucknar/Guide_Rancher_Monitoring#3]
I'm working on getting this set up and it is mostly working but I am having issues with the Graphite section.  In Grafana the Rancher Server stats are empty and it mentions modifying `graphite.host` but I'm not sure how to do that.

The guide says I should be able to visit `http://<SERVER_IP>:8080/v1/settings/graphite.host` but I don't see any of the containers exposing port 8080.  Is there something else I should do?  Any advice on what I should look at?

**Comment by jmreicha** [comment]
I think I figured it out.  I am using an Nginx proxy so just used the full DNS name of the rancher server instead of the Rancher server IP.

**Comment by Rucknar** [comment]
Yep, instructions could probably be clearer for that bit. I'll update them this weekend.

**Comment by jmreicha** [comment]
I wrote a [blog post](https://thepracticalsysadmin.com/easy-prometheus-monitoring-in-rancher/) about how to get this working and dropped you some links @Rucknar.

**Comment by Rucknar** [comment]
Awesome post man! Probably what this guide should of been...
Just had a quick skim through it, i'll have a proper read when i get back after the weekend. 

Kudos @jmreicha
